env:
  browser: true
  es6: true
  node: true
  jest: true
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "plugin:vue/vue3-strongly-recommended"
  - "prettier"
